from __future__ import annotations

import uuid
from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class CamelModel(BaseModel):
    """
    Spring/Jackson serializes DTOs as camelCase by default (auditId, rawTrace).
    This base class lets these models validate incoming camelCase JSON from the
    backend and emit camelCase JSON back to it, while still being usable from
    Python with normal snake_case attribute access.
    """

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)


class PriorReliability(CamelModel):
    """Matches Java's inner PriorReliability record structure."""

    reliability_score: int
    signal_summary: str  # Kept as str to match Java's String type
    recorded_at: str


class AuditJobMessage(CamelModel):
    """Shape of a message consumed from audit.jobs, matching Java exactly."""

    audit_id: str
    user_id: str
    title: Optional[str] = None
    raw_trace: str
    repo_name: Optional[str] = None
    agent_tool: Optional[str] = "generic"
    input_source: Optional[Literal["PASTED_TEXT", "FILE_UPLOAD", "CI_LOG", "PR_BUNDLE"]]
    prior_history: Optional[list[PriorReliability]] = Field(default_factory=list)
    suspicious_content: bool = False


class AuditReportPayload(CamelModel):
    """Explicit schema for the dictionary structure generated by run_audit."""

    overall_score: int
    executive_summary: str
    top_three_fixes: list
    loop_efficiency_report: dict
    blind_outcome_report: dict
    reliability_trend_report: dict
    extracted_evidence: dict
    withheld_claims: dict
    processing_time_ms: dict
    security_flags: dict = Field(default_factory=dict)


class AuditResultMessage(CamelModel):
    """Shape of a message published to audit.results."""

    audit_id: str
    status: Literal["COMPLETE", "FAILED"]
    report: Optional[AuditReportPayload] = None
    error: Optional[str] = None

class AuditProgressMessage(BaseModel):
    """Shape of a message published to audit.progress."""

    audit_id: uuid.UUID
    agent_type: Literal["TRACE_LOOP_EFFICIENCY", "BLIND_OUTCOME_VERIFIER", "RELIABILITY_TREND"]
    status: Literal["STARTED", "DONE"]
